Devops add: add stage secret scanning rev 4

diff --git a/.github/workflows/workflow-master.yml b/.github/workflows/workflow-master.yml
--- a/.github/workflows/workflow-master.yml
+++ b/.github/workflows/workflow-master.yml
@@ -5,31 +5,31 @@ on:
     branches: [master]
 
 jobs:
-  build:
+  secret-scanning:
     runs-on: ubuntu-latest
+    continue-on-error: true
     steps:
     - uses: actions/checkout@v3
     # Checkout Branch
     # List files to debug
-    - name: List workspace files
-      run: ls -al ${{ github.workspace }}
-
-    # Run TruffleHog inside Docker container
     - name: Secret Scanning with TruffleHog
       run: |
+        set +e  # Allow the script to continue even if TruffleHog fails
         docker run --rm \
-        -v ${{ github.workspace }}:/workspace \
-        -w /workspace \
-        trufflesecurity/trufflehog:latest filesystem . \
-        --exclude-paths trufflehog-excluded-paths.txt \
-        --fail --json --no-update > ${{ github.workspace }}/trufflehog-scan-result.json
+          -v ${{ github.workspace }}:/workspace \
+          -w /workspace \
+          trufflesecurity/trufflehog:latest filesystem . \
+          --exclude-paths trufflehog-excluded-paths.txt \
+          --fail --json --no-update > ${{ github.workspace }}/trufflehog-scan-result.json
+        set -e  # Re-enable the exit on error behavior
 
     # Archive the TruffleHog JSON result as an artifact
     - name: Archive TruffleHog Scan Result
+      if: always()  # Ensure this step always runs
       uses: actions/upload-artifact@v3
       with:
         name: trufflehog-scan-result
-        path: ./trufflehog-scan-result.json
+        path: ${{ github.workspace }}/trufflehog-scan-result.json
     # - uses: actions/checkout@v3
 
     # - name: Secret Scanning
